//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IRealTimeUnit")]
    public interface IRealTimeUnit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/PubInit", ReplyAction="http://tempuri.org/IRealTimeUnit/PubInitResponse")]
        void PubInit(string keyPath, int id, double low, double high, int add);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/PubInit", ReplyAction="http://tempuri.org/IRealTimeUnit/PubInitResponse")]
        System.Threading.Tasks.Task PubInitAsync(string keyPath, int id, double low, double high, int add);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/Write", ReplyAction="http://tempuri.org/IRealTimeUnit/WriteResponse")]
        void Write(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/Write", ReplyAction="http://tempuri.org/IRealTimeUnit/WriteResponse")]
        System.Threading.Tasks.Task WriteAsync(string message, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitChannel : RealTimeUnit.ServiceReference5.IRealTimeUnit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference5.IRealTimeUnit>, RealTimeUnit.ServiceReference5.IRealTimeUnit {
        
        public RealTimeUnitClient() {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PubInit(string keyPath, int id, double low, double high, int add) {
            base.Channel.PubInit(keyPath, id, low, high, add);
        }
        
        public System.Threading.Tasks.Task PubInitAsync(string keyPath, int id, double low, double high, int add) {
            return base.Channel.PubInitAsync(keyPath, id, low, high, add);
        }
        
        public void Write(string message, byte[] signature) {
            base.Channel.Write(message, signature);
        }
        
        public System.Threading.Tasks.Task WriteAsync(string message, byte[] signature) {
            return base.Channel.WriteAsync(message, signature);
        }
    }
}
