//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmDisplay.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IAlarm", CallbackContract=typeof(AlarmDisplay.ServiceReference3.IAlarmCallback))]
    public interface IAlarm {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarm/ConsoleSubInit")]
        void ConsoleSubInit();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarm/ConsoleSubInit")]
        System.Threading.Tasks.Task ConsoleSubInitAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarm/WriteToConsole", ReplyAction="http://tempuri.org/IAlarm/WriteToConsoleResponse")]
        void WriteToConsole(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarm/WriteToAlarmFile", ReplyAction="http://tempuri.org/IAlarm/WriteToAlarmFileResponse")]
        void WriteToAlarmFile(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmChannel : AlarmDisplay.ServiceReference3.IAlarm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmClient : System.ServiceModel.DuplexClientBase<AlarmDisplay.ServiceReference3.IAlarm>, AlarmDisplay.ServiceReference3.IAlarm {
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConsoleSubInit() {
            base.Channel.ConsoleSubInit();
        }
        
        public System.Threading.Tasks.Task ConsoleSubInitAsync() {
            return base.Channel.ConsoleSubInitAsync();
        }
    }
}
