//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendingConsoleApp.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ITrending", CallbackContract=typeof(TrendingConsoleApp.ServiceReference2.ITrendingCallback))]
    public interface ITrending {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/ConsoleTrendingInit")]
        void ConsoleTrendingInit();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/ConsoleTrendingInit")]
        System.Threading.Tasks.Task ConsoleTrendingInitAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/WriteToConsole", ReplyAction="http://tempuri.org/ITrending/WriteToConsoleResponse")]
        void WriteToConsole(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/WriteToLogFile", ReplyAction="http://tempuri.org/ITrending/WriteToLogFileResponse")]
        void WriteToLogFile(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/WriteToAlarmFile", ReplyAction="http://tempuri.org/ITrending/WriteToAlarmFileResponse")]
        void WriteToAlarmFile(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingChannel : TrendingConsoleApp.ServiceReference2.ITrending, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingClient : System.ServiceModel.DuplexClientBase<TrendingConsoleApp.ServiceReference2.ITrending>, TrendingConsoleApp.ServiceReference2.ITrending {
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConsoleTrendingInit() {
            base.Channel.ConsoleTrendingInit();
        }
        
        public System.Threading.Tasks.Task ConsoleTrendingInitAsync() {
            return base.Channel.ConsoleTrendingInitAsync();
        }
    }
}
